#!/usr/bin/env python
#-*- coding:utf-8-*- 

from tkinter import *

def yaz(x):
  global yazi
  yazi=yazi + x
  ekran.config(text=yazi)
	
def hesapla():
  global yazi
  a=eval(yazi)
  ekran.config(text=a)
  yazi=""
	
def temizle():
  global yazi
  ekran.config(text="")
  yazi=""

def sil():
  global yazi
  yazi=yazi[0:-1]
  ekran.config(text=yazi)
#bu bolumde hesap makinemizin isleyisi yer aliyor..

ftastemur=Tk()
ftastemur.geometry("340x280")
ftastemur.resizable(width=FALSE, height=FALSE)
ftastemur.title("hesap makinesi")
#ftastemur isimli bir pencere olusturduk.
#geometry komutu ile pencerenin boyutlarini belirttik.
#resizable komutu ile pencere boyutunun erisimini belirledik.
#FALSE erisime kapali(degistirilemez) anlamina gelmektedir..
#title ile pencereye bir baslik verdik.

cerceveana1=Frame()
cerceveana1.pack(expand=YES, fill=X)
#Frame() komutuyla bir cerceve olusturduk.
#pack bu cerceveyi gormemizi saglar.
#expand(); cercevenin pencere icerisindeki konumunu belirtir.
#expand=ortasinda olsun anlamina gelir.
#fill komutu cercevenin hangi eksende doldurulacagini belirtir.
#fill=X,Y,BOTH(x ekseni,y ekseni,her iki eksen) olabilir.

cerceveana11=Frame(cerceveana1)
cerceveana11.pack(side=TOP, expand=YES, fill=X)
#side yine cercevenin konumunu belirtir.
#side=TOP cerceve ust tarafa yaslanmis olsun anlaminda.
#side=(TOP,BOTTOM,LEFT,RIGHT) olabilir..
#sirasiyla(ust,alt,sol,sag)


cerceveana2=Frame()
cerceveana2.pack()

cerceveana21=Frame(cerceveana2)
cerceveana21.grid(row=0, column=0)
#grid() pencere araclarinin siralanacagi bir yapi.
#row=satir column=sutun
#yani cerceveana21 cerceveana2'nin 0.satir,0.sutun'unda yer alsin..

cerceveana22=Frame(cerceveana2)
cerceveana22.grid(row=0, column=1)

cerceveana23=Frame(cerceveana2)
cerceveana23.grid(row=1, column=0)

cerceveana24=Frame(cerceveana2)
cerceveana24.grid(row=1, column=1)

cerceve4=Frame(cerceveana21)
cerceve4.pack(padx=12)

cerceve2=Frame(cerceveana22)
cerceve2.pack(padx=12)

yazi=""
ekran=Label(cerceveana11)
ekran.config(textvariable=yazi,relief=SUNKEN,bg="#ffffff",height=2,anchor=E)
ekran.pack(expand=YES, fill=X, padx=12, pady=10)
#relief ile cercevemizin kabartma tipini belirledik..
#kabartma tipleri SUNKEN,SOLID,FLAT,RIDGE,GROOVE,RAISED...olabilir.

ben1=Label(cerceveana23)
ben1.config(text="Ramazan KARADAĞ", fg="black", bg="green", font=("Monotype Corsiva", 14, "italic"))
ben1.pack()
#config() komutu ile olusturdugumuz ben1 etiketini cerceveana23'e bagladik.
#font() komutuylada etiketimizin yazi tipini ve buyuklugunu belirttik.

ben2=Label(cerceveana24)
ben2.config(text="ByPIA", fg="black", bg="green", font=("Monotype Corsiva", 14, "italic"))
ben2.pack()
#pack() yaptigimiz cerceve,dugum,etiket..vs. goruntulememizi sagliyor..!
#pack yazmazsak kodu calistirdigimizda hic bir sey goremeyiz..


c=0
d=0
e=0
for i in (1,2,3,4,5,6,7,8,9):
	k=i%3
	if k==1:
		Button(cerceve4, text=i,fg="white",bg="blue",font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz(str(i)))).grid(row=c, column=1)
		c=c+1
	if k==2:
		Button(cerceve4, text=i,fg="white",bg="blue",font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz(str(i)))).grid(row=d, column=2)
		d=d+1
	if k==0:
		Button(cerceve4, text=i,fg="white",bg="blue",font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz(str(i)))).grid(row=e, column=3)
		e=e+1
#burda kullanacagimiz rakamlari yazdik lambda notasyonu yardimiyla..
#height-width kullanacagimiz butonlarin(cerceve dugumleri) eni ve boyu olarak dusunulebilir..
		
	
Button(cerceve2, text="X",fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("*"))).grid(row=0, column=4)
Button(cerceve2, text="/",fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("/"))).grid(row=1, column=4)
Button(cerceve2, text="=", fg="yellow",bg="red",font=("Arial", 10, "bold"), height=2, width=6, command=hesapla).grid(row=2, column=4)
Button(cerceve4, text="(",fg="white",bg="blue", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("("))).grid(row=3, column=1)
Button(cerceve4, text="0",fg="white",bg="blue", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("0"))).grid(row=3, column=2)
Button(cerceve4, text=")",fg="white",bg="blue", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz(")"))).grid(row=3, column=3)
Button(cerceve2, text="AC",fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=temizle).grid(row=3, column=4)
Button(cerceve2, text="+",fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("+"))).grid(row=0, column=5)
Button(cerceve2, text="-",fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("-"))).grid(row=1, column=5)
Button(cerceve2, text=".",fg="yellow",bg="red",font=("Arial", 10, "bold"), height=2, width=6, command=(lambda i=i: yaz("."))).grid(row=2, column=5)
Button(cerceve2, text="C", fg="yellow",bg="red", font=("Arial", 10, "bold"), height=2, width=6, command=sil).grid(row=3, column=5)
#burdada isleclerimiz var..
#fg(frontground)=on plan rengi..
#bg(background)=arka plan rengi..
#font() komutu ile yine yazi tipini belirledik..
#grid() komutu ile islec butonlarinin konumunu belirttik..
#row=satir,column=sutun

ftastemur.mainloop()
